name: 'flutter_open_chinese_convert'
version: 0.3.3
homepage: 'https://github.com/zonble/flutter_open_chinese_convert'
environment: 
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=1.20.0'
description: 'flutter_open_chinese_convert bridges OpenCC (Open Chinese Convert) to your Flutter projects.'
dependencies: 
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_lints: any
  flutter_test: 
    sdk: flutter
  import_sorter: '^4.6.0'
  pubspec_dependency_sorter: '^1.0.4'
flutter: 
  plugin: 
    platforms: 
      android: 
        package: 'net.zonble.flutter_open_chinese_convert'
        pluginClass: FlutterOpenccPlugin
      ios: 
        pluginClass: FlutterOpenccPlugin
import_sorter: 
  emojis: false
  comments: false
